export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const ON_FORM_SUBMIT = "ON_FORM_SUBMIT";
export const APPLICATION_FETCH_LOADING = "APPLICATION_FETCH_LOADING";
export const APPLICATION_FETCH_SUCCESS = "APPLICATION_FETCH_SUCCESS";
